install:
  - ps: Start-FileDownload "https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe"
  - rustup-init.exe -y --default-host i686-pc-windows-gnu
  - SET PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V

build:
  - cargo build --verbose --no-default-features --feature default-minimal

test_script:
  - cargo test --verbose --no-default-features --feature default-minimal