---
# Do not check this file into version control!
#
# This file contains the "secrets" used by your application, including
# passwords, API tokens, etc.  These secrets will be added to the
# appropriate containers when we generate the final `*.yml` files.
#
# For a more secure alternative, try using cage's `vault` support.

# You can share secrets between all containers.
common:
  GLOBAL_PASSWORD: "magic"

# You can specify secrets by pod.
pods:
  frontend:
    web:
      SOME_PASSWORD: "secret"

# You can override secrets by environment.
targets:
  production:
    common:
      GLOBAL_PASSWORD: "more magic"
      DATABASE_URL: "postgres://postgres:mypass@db:5432/rails_hello_production"
    pods:
      frontend:
        web:
          SOME_PASSWORD: "production secret"
