version: "2"
services:
  web:
    image: "dockercloud/hello-world"
    build: "https://github.com/docker/dockercloud-hello-world.git"
    ports:
      - "3000"
    hostname: "hello-world"
      
  proxy:
    image: "dockercloud/haproxy"
    build: "https://github.com/docker/dockercloud-haproxy.git"
    ports:
      - "8080:80"
    links:
      - "web"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    # We can use `org.fdy.conductor` labels to override some common
    # defaults.
    labels:
      # Specify the shell used by `conductor shell`.  Defaults to `sh`.
      io.fdy.conductor.shell: "/bin/sh"
      # Specify how to run the service's internal tests.  May use shell
      # quoting but not shell variables.
      io.fdy.conductor.test: "echo 'All tests passed'"
